// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsnD64JvfbXrzpDM9ItdPg9i9qtvdVIc',
    appId: '1:860395547039:web:478a19d91299c0d7d875aa',
    messagingSenderId: '860395547039',
    projectId: 'flutter-course-8d188',
    authDomain: 'flutter-course-8d188.firebaseapp.com',
    storageBucket: 'flutter-course-8d188.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiko9SEU9ou1BDxuHLzG9D7RK28zn4G-0',
    appId: '1:860395547039:android:bf03469479b60e9cd875aa',
    messagingSenderId: '860395547039',
    projectId: 'flutter-course-8d188',
    storageBucket: 'flutter-course-8d188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtuRcVG0hjh2jzgYs3og17PtX7ThxaSmU',
    appId: '1:860395547039:ios:fe70be71223528b4d875aa',
    messagingSenderId: '860395547039',
    projectId: 'flutter-course-8d188',
    storageBucket: 'flutter-course-8d188.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuRcVG0hjh2jzgYs3og17PtX7ThxaSmU',
    appId: '1:860395547039:ios:021d33445b6e1411d875aa',
    messagingSenderId: '860395547039',
    projectId: 'flutter-course-8d188',
    storageBucket: 'flutter-course-8d188.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
